// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: firstrpcdemo.proto

package server

import (
	"context"

	"firstrpcdemo/firstrpcdemo"
	"firstrpcdemo/internal/logic"
	"firstrpcdemo/internal/svc"
)

type FirstrpcdemoServer struct {
	svcCtx *svc.ServiceContext
	firstrpcdemo.UnimplementedFirstrpcdemoServer
}

func NewFirstrpcdemoServer(svcCtx *svc.ServiceContext) *FirstrpcdemoServer {
	return &FirstrpcdemoServer{
		svcCtx: svcCtx,
	}
}

func (s *FirstrpcdemoServer) Ping(ctx context.Context, in *firstrpcdemo.Request) (*firstrpcdemo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
