// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"gozeroapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/focus",
				Handler: GetFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/focus/:id",
				Handler: GetFocusByIdHandler(serverCtx),
			},
		},
	)
}
