// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	focus "gozeroapi/internal/handler/focus"
	"gozeroapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/focus",
				Handler: focus.GetFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/focus/:id",
				Handler: focus.GetFocusWithIdByPathHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/focus/body",
				Handler: focus.GetFocusWithIdByBodyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/focus/query",
				Handler: focus.GetFocusWithIdByQueryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
