// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Address struct {
	Id      int64  `json:"id"`
	Address string `json:"address"`
	Phone   string `json:"phone"`
	Name    string `json:"name"`
}

type Book struct {
	Id       int     `json:"id"`
	Bookname string  `json:"bookname"`
	Price    float64 `json:"price"`
}

type BookAdd struct {
	Bookname string  `json:"bookname"`
	Price    float64 `json:"price"`
}

type BookQuestById struct {
	Id int `path:"id"`
}

type BookSQL struct {
	Id int `json:"id"`
}

type BookWhere struct {
	Bookname string `json:"bookname"`
}

type CommonResponse struct {
	Success bool        `json:"success"`
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type LessonIdReq struct {
	LessonId int `path:"lessonId"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type StudentIdReq struct {
	StudentId int `path:"studentId"`
}
