// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/userInfo.proto

package userService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Userinfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Hobby         []string               `protobuf:"bytes,3,rep,name=hobby,proto3" json:"hobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Userinfo) Reset() {
	*x = Userinfo{}
	mi := &file_proto_userInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Userinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userinfo) ProtoMessage() {}

func (x *Userinfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userinfo.ProtoReflect.Descriptor instead.
func (*Userinfo) Descriptor() ([]byte, []int) {
	return file_proto_userInfo_proto_rawDescGZIP(), []int{0}
}

func (x *Userinfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Userinfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Userinfo) GetHobby() []string {
	if x != nil {
		return x.Hobby
	}
	return nil
}

var File_proto_userInfo_proto protoreflect.FileDescriptor

const file_proto_userInfo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/userInfo.proto\x12\buserinfo\"N\n" +
	"\buserinfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x14\n" +
	"\x05hobby\x18\x03 \x03(\tR\x05hobbyB\x0fZ\r./userServiceb\x06proto3"

var (
	file_proto_userInfo_proto_rawDescOnce sync.Once
	file_proto_userInfo_proto_rawDescData []byte
)

func file_proto_userInfo_proto_rawDescGZIP() []byte {
	file_proto_userInfo_proto_rawDescOnce.Do(func() {
		file_proto_userInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userInfo_proto_rawDesc), len(file_proto_userInfo_proto_rawDesc)))
	})
	return file_proto_userInfo_proto_rawDescData
}

var file_proto_userInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_userInfo_proto_goTypes = []any{
	(*Userinfo)(nil), // 0: userinfo.userinfo
}
var file_proto_userInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_userInfo_proto_init() }
func file_proto_userInfo_proto_init() {
	if File_proto_userInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userInfo_proto_rawDesc), len(file_proto_userInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_userInfo_proto_goTypes,
		DependencyIndexes: file_proto_userInfo_proto_depIdxs,
		MessageInfos:      file_proto_userInfo_proto_msgTypes,
	}.Build()
	File_proto_userInfo_proto = out.File
	file_proto_userInfo_proto_goTypes = nil
	file_proto_userInfo_proto_depIdxs = nil
}
