// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: firstrpcdemo.proto

package firstrpcdemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Firstrpcdemo_Ping_FullMethodName = "/firstrpcdemo.Firstrpcdemo/Ping"
)

// FirstrpcdemoClient is the client API for Firstrpcdemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirstrpcdemoClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type firstrpcdemoClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstrpcdemoClient(cc grpc.ClientConnInterface) FirstrpcdemoClient {
	return &firstrpcdemoClient{cc}
}

func (c *firstrpcdemoClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Firstrpcdemo_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstrpcdemoServer is the server API for Firstrpcdemo service.
// All implementations must embed UnimplementedFirstrpcdemoServer
// for forward compatibility.
type FirstrpcdemoServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFirstrpcdemoServer()
}

// UnimplementedFirstrpcdemoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirstrpcdemoServer struct{}

func (UnimplementedFirstrpcdemoServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFirstrpcdemoServer) mustEmbedUnimplementedFirstrpcdemoServer() {}
func (UnimplementedFirstrpcdemoServer) testEmbeddedByValue()                      {}

// UnsafeFirstrpcdemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirstrpcdemoServer will
// result in compilation errors.
type UnsafeFirstrpcdemoServer interface {
	mustEmbedUnimplementedFirstrpcdemoServer()
}

func RegisterFirstrpcdemoServer(s grpc.ServiceRegistrar, srv FirstrpcdemoServer) {
	// If the following call panics, it indicates UnimplementedFirstrpcdemoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Firstrpcdemo_ServiceDesc, srv)
}

func _Firstrpcdemo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstrpcdemoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firstrpcdemo_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstrpcdemoServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Firstrpcdemo_ServiceDesc is the grpc.ServiceDesc for Firstrpcdemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Firstrpcdemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "firstrpcdemo.Firstrpcdemo",
	HandlerType: (*FirstrpcdemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Firstrpcdemo_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firstrpcdemo.proto",
}
