// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	account "gozerogorm/internal/handler/account"
	address "gozerogorm/internal/handler/address"
	bookmetadata "gozerogorm/internal/handler/bookmetadata"
	books "gozerogorm/internal/handler/books"
	lesson "gozerogorm/internal/handler/lesson"
	student "gozerogorm/internal/handler/student"
	"gozerogorm/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: account.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/address/list",
				Handler: address.AddressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: bookmetadata.GetBookAndMetadataHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/bookmetadata"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: books.GetUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: books.AddBookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bookmetadata",
				Handler: books.GetBookAndMetadataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/index",
				Handler: books.GetbooksHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sql",
				Handler: books.SQLBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/where",
				Handler: books.WhereBookHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/book"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/lessonStudents",
				Handler: lesson.GetLessonStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: lesson.GetLessonListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oneLesson/:lessonId",
				Handler: lesson.GetOneLessonHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/lesson"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: student.GetStudentListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oneStudent/:studentId",
				Handler: student.GetOneStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/studentCourses/:studentId",
				Handler: student.GetStudentCoursesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/student"),
	)
}
