// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	bookmetadata "gozerogorm/internal/handler/bookmetadata"
	books "gozerogorm/internal/handler/books"
	"gozerogorm/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: bookmetadata.GetBookAndMetadataHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/bookmetadata"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: books.GetUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: books.AddBookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getbookmetadata",
				Handler: books.GetBookAndMetadataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/index",
				Handler: books.GetbooksHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sql",
				Handler: books.SQLBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/where",
				Handler: books.WhereBookHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/book"),
	)
}
