// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: greeter.proto

package server

import (
	"context"

	"greeter/greeter"
	"greeter/internal/logic"
	"greeter/internal/svc"
)

type GreeterServer struct {
	svcCtx *svc.ServiceContext
	greeter.UnimplementedGreeterServer
}

func NewGreeterServer(svcCtx *svc.ServiceContext) *GreeterServer {
	return &GreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *GreeterServer) SayHello(ctx context.Context, in *greeter.HelloReq) (*greeter.HelloRes, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
