// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: goods.proto

package goodsserviceclient

import (
	"context"

	"proto_demo/goodsService"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGoodsReq = goodsService.AddGoodsReq
	AddGoodsRes = goodsService.AddGoodsRes
	GetGoodsReq = goodsService.GetGoodsReq
	GetGoodsRes = goodsService.GetGoodsRes
	GoodsModel  = goodsService.GoodsModel

	GoodsService interface {
		AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsRes, error)
		GetGoods(ctx context.Context, in *GetGoodsReq, opts ...grpc.CallOption) (*GetGoodsRes, error)
	}

	defaultGoodsService struct {
		cli zrpc.Client
	}
)

func NewGoodsService(cli zrpc.Client) GoodsService {
	return &defaultGoodsService{
		cli: cli,
	}
}

func (m *defaultGoodsService) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsRes, error) {
	client := goodsService.NewGoodsServiceClient(m.cli.Conn())
	return client.AddGoods(ctx, in, opts...)
}

func (m *defaultGoodsService) GetGoods(ctx context.Context, in *GetGoodsReq, opts ...grpc.CallOption) (*GetGoodsRes, error) {
	client := goodsService.NewGoodsServiceClient(m.cli.Conn())
	return client.GetGoods(ctx, in, opts...)
}
