// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: goods.proto

package server

import (
	"context"

	"proto_demo/goodsService"
	"proto_demo/internal/logic"
	"proto_demo/internal/svc"
)

type GoodsServiceServer struct {
	svcCtx *svc.ServiceContext
	goodsService.UnimplementedGoodsServiceServer
}

func NewGoodsServiceServer(svcCtx *svc.ServiceContext) *GoodsServiceServer {
	return &GoodsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServiceServer) AddGoods(ctx context.Context, in *goodsService.AddGoodsReq) (*goodsService.AddGoodsRes, error) {
	l := logic.NewAddGoodsLogic(ctx, s.svcCtx)
	return l.AddGoods(in)
}

func (s *GoodsServiceServer) GetGoods(ctx context.Context, in *goodsService.GetGoodsReq) (*goodsService.GetGoodsRes, error) {
	l := logic.NewGetGoodsLogic(ctx, s.svcCtx)
	return l.GetGoods(in)
}
