// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"client/m4api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sayhello",
				Handler: SayHelloGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sayhello",
				Handler: SayHelloPostHandler(serverCtx),
			},
		},
	)
}
