// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResponse struct {
	Success bool        `json:"success"`
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Focus struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Title string `json:"title"`
	Link  string `json:"link"`
}

type FocusRequest struct {
	Id string `path:id` // 访问路径传值
}

type Request struct {
}

type Response struct {
}
