// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResponse struct {
	Success bool        `json:"success"`
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"` // omitempty表示此字段可选择不返回值
}

type Focus struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Title string `json:"title"`
	Link  string `json:"link"`
}

type FocusRequestByBody struct {
	Id string `form:"id"` // 表单传值
}

type FocusRequestByPath struct {
	Id string `path:"id"` // 动态路由传值 /:id 术语：路径参数（Path Parameter）或 URL 参数（URL Parameter）
}

type FocusRequestByQuery struct {
	Id string `form:"id,default='1145'"` // 查询传值 ?id=123 术语：查询参数（Query Parameter）或 查询字符串（Query String）
}

type Request struct {
}

type Response struct {
}
