// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: firstrpcdemo.proto

package firstrpcdemoclient

import (
	"context"

	"firstrpcdemo/firstrpcdemo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = firstrpcdemo.Request
	Response = firstrpcdemo.Response

	Firstrpcdemo interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultFirstrpcdemo struct {
		cli zrpc.Client
	}
)

func NewFirstrpcdemo(cli zrpc.Client) Firstrpcdemo {
	return &defaultFirstrpcdemo{
		cli: cli,
	}
}

func (m *defaultFirstrpcdemo) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := firstrpcdemo.NewFirstrpcdemoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
